<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Products\Product;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {


        $products = [
            ['name' => 'Blusa Leve Light Running UV50+', 'description' => 'Blusa Leve Light Running UV50+ 1', 'sku' => 'FT31JAZTL0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '78.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 3,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 1, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Blusa Leve Light Running UV50+', 'description' => 'Blusa Leve Light Running UV50+ 5', 'sku' => 'FT31JBRTL0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '78.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 3,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 2, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Blusa Leve Light Running UV50+', 'description' => 'Blusa Leve Light Running UV50+ 9', 'sku' => 'FT31JTPTL0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '78.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 3,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 3, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Blusa Leve Graphen UV50+', 'description' => 'Blusa Leve Graphen UV50+ 1', 'sku' => 'FT31JAZTL0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '106.80',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 3,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 4, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Blusa Leve Graphen UV50+', 'description' => 'Blusa Leve Graphen UV50+ 5', 'sku' => 'FT31JBRTL0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '106.80',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 3,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 5, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Blusa Leve Graphen UV50+', 'description' => 'Blusa Leve Graphen UV50+ 9', 'sku' => 'FT31JTPTL0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '106.80',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 3,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 6, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Blusa Leve Graphen UV50+', 'description' => 'Blusa Leve Graphen UV50+ 13', 'sku' => '', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '106.80',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 3,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 7, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Blusa Leve Graphen UV50+', 'description' => 'Blusa Leve Graphen UV50+ 17', 'sku' => '', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '106.80',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 3,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 8, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camisa Manga Longa UV50+', 'description' => 'Camisa Manga Longa UV50+ 1', 'sku' => 'T31TTAML0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '46.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 1,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 1, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camisa Manga Longa UV50+', 'description' => 'Camisa Manga Longa UV50+ 5', 'sku' => 'T31TTBRL0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '46.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 1,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 2, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['Name' => 'Camisa Manga Longa UV50+', 'description' => 'Camisa Manga Longa UV50+ 9', 'sku' => 'T31TTPTL0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '46.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 1,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 3, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camisa Manga Longa UV50+', 'description' => 'Camisa Manga Longa UV50+ 13', 'sku' => 'T31TTABL0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '46.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 1,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 9, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camisa Manga Longa UV50+', 'description' => 'Camisa Manga Longa UV50+ 17', 'sku' => 'T31TTBAL0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '46.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 1,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 10, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camisa Manga Longa UV50+', 'description' => 'Camisa Manga Longa UV50+ 21', 'sku' => 'T31TTPBL0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '46.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 1,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 11, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camisa Manga Longa UV50+', 'description' => 'Camisa Manga Longa UV50+ 25', 'sku' => 'T31TTBPL0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '46.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 1,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 12, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camisa Manga Longa UV50+', 'description' => 'Camisa Manga Longa UV50+ 29', 'sku' => 'T31TCPAL0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '46.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 1,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 13, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camisa Manga Longa UV50+', 'description' => 'Camisa Manga Longa UV50+ 33', 'sku' => 'T31TCPCL0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '46.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 1,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 14, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camisa Manga Longa UV50+', 'description' => 'Camisa Manga Longa UV50+ 37', 'sku' => 'T31TCPGL0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '46.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 1,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 15, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camisa Manga Longa UV50+', 'description' => 'Camisa Manga Longa UV50+ 41', 'sku' => 'T31TCPVL0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '46.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 1,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 16, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camiseta UV50+', 'description' => 'Camisa UV50+ 1', 'sku' => 'T33TTAMC0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '42.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 3,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 1, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camiseta UV50+', 'description' => 'Camisa UV50+ 5', 'sku' => 'T33TTBRC0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '42.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 3,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 2, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camiseta UV50+', 'description' => 'Camisa UV50+ 9', 'sku' => 'T33TTPTC0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '42.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 3,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 3, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camisa Manga Longa UV50+ Feminina', 'description' => 'Camisa Manga Longa UV50+ Feminina 1', 'sku' => 'T30TTPTL0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '46.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 1,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 3, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camisa Manga Longa UV50+ Feminina', 'description' => 'Camisa Manga Longa UV50+ Feminina 5', 'sku' => 'T30TTBRL0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '46.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 1,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 2, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camisa Manga Longa UV50+ Feminina', 'description' => 'Camisa Manga Longa UV50+ Feminina 9', 'sku' => 'T30TTRSL0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '46.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 1,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 17, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camisa Manga Longa UV50+ Feminina', 'description' => 'Camisa Manga Longa UV50+ Feminina 13', 'sku' => 'T30TTACL0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '46.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 1,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 18, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camisa Manga Longa UV50+ Feminina', 'description' => 'Camisa Manga Longa UV50+ Feminina 17', 'sku' => 'T30TTAPL0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '46.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 1,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 19, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camisa Manga Longa UV50+ Feminina', 'description' => 'Camisa Manga Longa UV50+ Feminina 21', 'sku' => 'T30TTPAL0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '46.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 1,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 20, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camisa Manga Longa UV50+ Feminina', 'description' => 'Camisa Manga Longa UV50+ Feminina 25', 'sku' => 'T30TTRPL0', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '46.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 1,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 21, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camisa Manga Longa UV50+ Feminina', 'description' => 'Camisa Manga Longa UV50+ Feminina 29', 'sku' => 'T30TTPRL)', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '46.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 1,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 22, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camisa Ninja UV50+', 'description' => 'Camisa Ninja UV50+ 1', 'sku' => 'T31TNAZ', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '64.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 1,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 1, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camisa Ninja UV50+', 'description' => 'Camisa Ninja UV50+ 5', 'sku' => 'T31TNBR', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '64.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 1,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 2, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Camisa Ninja UV50+', 'description' => 'Camisa Ninja UV50+ 9', 'sku' => 'T31TNPT', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '64.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 1,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 3, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Jaqueta Esportiva', 'description' => 'Jaqueta Esportiva 1', 'sku' => 'T31TNAZ', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '78.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 4,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 1, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Jaqueta Esportiva', 'description' => 'Jaqueta Esportiva 8', 'sku' => 'T31TNAZ', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '78.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 4,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 2, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Jaqueta Esportiva', 'description' => 'Jaqueta Esportiva 9', 'sku' => 'T31TNAZ', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '78.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 4,  'subgroup_id' => 1,  'collection_id' => 1, 'brand_id' => 1, 'color_id' => 3, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Manguito', 'description' => 'Manguito 1', 'sku' => 'T32MGAZ10', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '23.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 5,  'subgroup_id' => 1, 'collection_id' => 1, 'brand_id' => 1, 'color_id' => 1, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Manguito', 'description' => 'Manguito 2', 'sku' => 'T32MGBR10', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '23.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 5,  'subgroup_id' => 1, 'collection_id' => 1, 'brand_id' => 1, 'color_id' => 2, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Manguito', 'description' => 'Manguito 3', 'sku' => 'T32MGPT10', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '23.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 5,  'subgroup_id' => 1, 'collection_id' => 1, 'brand_id' => 1, 'color_id' => 3, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Manguito', 'description' => 'Manguito 4', 'sku' => 'T32MCAZ20', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '23.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 5,  'subgroup_id' => 1, 'collection_id' => 1, 'brand_id' => 1, 'color_id' => 13, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Manguito', 'description' => 'Manguito 5', 'sku' => 'T32MGBR20', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '23.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 5,  'subgroup_id' => 1, 'collection_id' => 1, 'brand_id' => 1, 'color_id' => 14, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Manguito', 'description' => 'Manguito 6', 'sku' => 'T32MGPT20', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '23.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 5,  'subgroup_id' => 1, 'collection_id' => 1, 'brand_id' => 1, 'color_id' => 15, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Manguito', 'description' => 'Manguito 7', 'sku' => 'T32MGPT20', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '23.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 5,  'subgroup_id' => 1, 'collection_id' => 1, 'brand_id' => 1, 'color_id' => 16, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Manguito C/ Encaixe para dedo', 'description' => 'Manguito C/ Encaixe para dedo 1', 'sku' => 'T32MGAZ20', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '26.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 5,  'subgroup_id' => 1, 'collection_id' => 1, 'brand_id' => 1, 'color_id' => 1, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Manguito C/ Encaixe para dedo', 'description' => 'Manguito C/ Encaixe para dedo 2', 'sku' => 'T32MGBR20', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '26.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 5,  'subgroup_id' => 1, 'collection_id' => 1, 'brand_id' => 1, 'color_id' => 2, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Manguito C/ Encaixe para dedo', 'description' => 'Manguito C/ Encaixe para dedo 3', 'sku' => 'T32MGPT20', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '26.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 5,  'subgroup_id' => 1, 'collection_id' => 1, 'brand_id' => 1, 'color_id' => 3, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Manguito C/ Encaixe para dedo', 'description' => 'Manguito C/ Encaixe para dedo 4', 'sku' => 'T32MCAZ20', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '26.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 5,  'subgroup_id' => 1, 'collection_id' => 1, 'brand_id' => 1, 'color_id' => 13, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Manguito C/ Encaixe para dedo', 'description' => 'Manguito C/ Encaixe para dedo 5', 'sku' => 'T32MGBR20', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '26.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 5,  'subgroup_id' => 1, 'collection_id' => 1, 'brand_id' => 1, 'color_id' => 14, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Manguito C/ Encaixe para dedo', 'description' => 'Manguito C/ Encaixe para dedo 6', 'sku' => 'T32MGPT20', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '26.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 5,  'subgroup_id' => 1, 'collection_id' => 1, 'brand_id' => 1, 'color_id' => 15, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Manguito C/ Encaixe para dedo', 'description' => 'Manguito C/ Encaixe para dedo 7', 'sku' => 'T32MGPT20', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '26.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 5,  'subgroup_id' => 1, 'collection_id' => 1, 'brand_id' => 1, 'color_id' => 16, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Bandana', 'description' => 'Bandana 1', 'sku' => 'T32BSAM20', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '26.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 6,  'subgroup_id' => 1, 'collection_id' => 1, 'brand_id' => 1, 'color_id' => 1, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Bandana', 'description' => 'Bandana 2', 'sku' => 'T32BSBR20', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '26.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 6,  'subgroup_id' => 1, 'collection_id' => 1, 'brand_id' => 1, 'color_id' => 2, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'Bandana', 'description' => 'Bandana 3', 'sku' => 'T32BSPT20', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '26.00',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 6,  'subgroup_id' => 1, 'collection_id' => 1, 'brand_id' => 1, 'color_id' => 3, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],
            ['name' => 'PERNITOS PROTEÇÃO UV50+ ', 'description' => 'PERNITOS PROTEÇÃO UV50+ ', 'sku' => '', 'qr_code' => '', 'barcode' => '', 'purchase_price' => '46.55',  'stock' =>  0, 'image' => '',   'category_id' => 1,  'subcategory_id' => 1,  'group_id' => 7,  'subgroup_id' => 1, 'collection_id' => 1, 'brand_id' => 1, 'color_id' => 3, 'action_user' => 'Criado por: Seeder em ' . now(),  'discontinued' => false,],

        ];

        foreach ($products as $product) {
            $product['cost_price'] = $product['purchase_price'] * 1.1;
            $product['promotion_price'] = $product['purchase_price'] * 1.5;
            $product['sale_price'] = $product['purchase_price'] * 1.8;

            Product::create($product);
        }
    }
}
//php artisan db:seed --class=ProductSeeder
